bootstrap.servers=localhost:9092

topic.raw.documents=raw-documents

acks=all
retries=3
linger.ms=5
batch.size=16384
compression.type=snappy

# path relative to project root
dataset.path=Data/20newsgroups.jsonl

# ms between messages
producer.rate.ms=100

drift.enabled=true
drift.gradual.window=200
drift.recurring.period=150