bootstrap.servers=localhost:9092
application.id=anomaly-streams-v1

topic.input=raw-documents
topic.output.sliding=preprocessed-batches-sliding

window.strategy=SLIDING
# 60s window, slides every 15s
window.sliding.size.seconds=60
window.sliding.advance.seconds=15

# drop tiny batches at startup
window.min.batch.size=5

num.stream.threads=6
state.dir=/tmp/kafka-streams/anomaly